
from django.core.management.base import BaseCommand
from tickets.models import Route

class Command(BaseCommand):
    help = 'Populate the database with initial route data'

    def handle(self, *args, **kwargs):
        routes = [
            {'source': 'Barasat', 'destination': 'Dum Dum', 'price': 5},
            {'source': 'Barasat', 'destination': 'Madhyamgram', 'price': 5},
            {'source': 'Barasat', 'destination': 'Dattapukur', 'price': 5},
            {'source': 'Barasat', 'destination': 'Sealdah', 'price': 10},
            {'source': 'Barasat', 'destination': 'Habra', 'price': 10},
            {'source': 'Barasat', 'destination': 'Bidhannagar', 'price': 10},
            {'source': 'Barasat', 'destination': 'Howrah', 'price': 10},
            {'source': 'Barasat', 'destination': 'Kolkata', 'price': 10},
            {'source': 'Barasat', 'destination': 'Bongaon', 'price': 15},
            {'source': 'Barasat', 'destination': 'Gobardanga', 'price': 10},
            {'source': 'Barasat', 'destination': 'Thakurnagar', 'price': 15},
            {'source': 'Barasat', 'destination': 'Naihati', 'price': 15},
            {'source': 'Barasat', 'destination': 'Barrackpore', 'price': 5},
            {'source': 'Barasat', 'destination': 'Sodepur', 'price': 5},
            {'source': 'Barasat', 'destination': 'Belgharia', 'price': 10},
            {'source': 'Barasat', 'destination': 'Shyamnagar', 'price': 15},
            {'source': 'Barasat', 'destination': 'Kanchrapara', 'price': 20},
            {'source': 'Barasat', 'destination': 'Ranaghat', 'price': 20},
            {'source': 'Barasat', 'destination': 'Krishnanagar', 'price': 20},
            {'source': 'Barasat', 'destination': 'New Barrackpore', 'price': 5},
            {'source': 'Barasat', 'destination': 'Hridaypur', 'price': 5},
            {'source': 'Barasat', 'destination': 'Birati', 'price': 5},
            {'source': 'Barasat', 'destination': 'Dakshineswar', 'price': 10},
            {'source': 'Barasat', 'destination': 'Titagarh', 'price': 10},
            {'source': 'Barasat', 'destination': 'Kankinara', 'price': 10},
            {'source': 'Barasat', 'destination': 'Khardah', 'price': 10},
            {'source': 'Barasat', 'destination': 'Park Circus', 'price': 10},
            {'source': 'Barasat', 'destination': 'Ballygunge Jn', 'price': 10},
            {'source': 'Barasat', 'destination': 'Dhakuria', 'price': 10},
            {'source': 'Barasat', 'destination': 'Jadabpur', 'price': 10},
            {'source': 'Barasat', 'destination': 'Bagha Jatin', 'price': 10},
            {'source': 'Barasat', 'destination': 'New Garia', 'price': 10},
            {'source': 'Barasat', 'destination': 'Garia', 'price': 10},
            {'source': 'Barasat', 'destination': 'Narendrapur', 'price': 15},
            {'source': 'Barasat', 'destination': 'Sonarpur Jn', 'price': 15},
            {'source': 'Barasat', 'destination': 'Bidyadharpur', 'price': 15},
            {'source': 'Barasat', 'destination': 'Kalikapur', 'price': 15},
            {'source': 'Barasat', 'destination': 'Champahati', 'price': 15},
            {'source': 'Barasat', 'destination': 'Piali', 'price': 15},
            {'source': 'Barasat', 'destination': 'Gaurdaha', 'price': 15},
            {'source': 'Barasat', 'destination': 'Ghutiari Sharif', 'price': 15},
            {'source': 'Barasat', 'destination': 'Betberia Ghola', 'price': 15},
            {'source': 'Barasat', 'destination': 'Taldi', 'price': 15},
            {'source': 'Barasat', 'destination': 'Canning', 'price': 15},
            {'source': 'Barasat', 'destination': 'Bamangacchi', 'price': 5},
            {'source': 'Barasat', 'destination': 'Bira', 'price': 5},
            {'source': 'Barasat', 'destination': 'Guma', 'price': 5},
            {'source': 'Barasat', 'destination': 'Ashok Nagar Road', 'price': 5},
            {'source': 'Barasat', 'destination': 'Sanhati', 'price': 10},
            {'source': 'Barasat', 'destination': 'Machhalandapur', 'price': 10},
            {'source': 'Barasat', 'destination': 'Chandpara', 'price': 15},
            {'source': 'Barasat', 'destination': 'Majerhat', 'price': 10},
            {'source': 'Barasat', 'destination': 'Dumdum Cantonment', 'price': 5},
            {'source': 'Barasat', 'destination': 'Durganagar', 'price': 5},
            {'source': 'Barasat', 'destination': 'Bidhannagar Road', 'price': 10},
            {'source': 'Barasat', 'destination': 'Sir Gurudass Banerjee', 'price': 10},
            {'source': 'Barasat', 'destination': 'Beleghata Road', 'price': 10},
            {'source': 'Barasat', 'destination': 'Kankurgachi Road', 'price': 10},
            {'source': 'Barasat', 'destination': 'Bally', 'price': 10},
            {'source': 'Barasat', 'destination': 'Belur', 'price': 10},
            {'source': 'Barasat', 'destination': 'Liluah', 'price': 10},
            {'source': 'Barasat', 'destination': 'Santragachi Jn', 'price': 15},
            {'source': 'Barasat', 'destination': 'Andul', 'price': 15},
            {'source': 'Barasat', 'destination': 'Shalimar', 'price': 15},
            {'source': 'Barasat', 'destination': 'Dankuni Jn', 'price': 15},
            {'source': 'Barasat', 'destination': 'Bally Ghat', 'price': 10},
            {'source': 'Barasat', 'destination': 'Uttarpara', 'price': 10},
            {'source': 'Barasat', 'destination': 'Hind Motor', 'price': 10},
            {'source': 'Barasat', 'destination': 'Konnagar', 'price': 10},
            {'source': 'Barasat', 'destination': 'Rishra', 'price': 10},
            {'source': 'Barasat', 'destination': 'Serampore', 'price': 10},
            {'source': 'Barasat', 'destination': 'Seoraphuli Jn', 'price': 10},
            {'source': 'Barasat', 'destination': 'Baidyabati', 'price': 10},
            {'source': 'Barasat', 'destination': 'Chandan Nagar', 'price': 15},
            {'source': 'Barasat', 'destination': 'Chuchura', 'price': 15},
            {'source': 'Barasat', 'destination': 'Hooghly', 'price': 15},
            {'source': 'Barasat', 'destination': 'Bandel Jn', 'price': 15},
            {'source': 'Barasat', 'destination': 'Naihati Jn', 'price': 15},
            {'source': 'Barasat', 'destination': 'Halisahar', 'price': 15},
            {'source': 'Barasat', 'destination': 'Kalyani', 'price': 20},
            {'source': 'Barasat', 'destination': 'Kalyani Ghoshpara', 'price': 20},
            {'source': 'Barasat', 'destination': 'Chakdaha', 'price': 20},
            {'source': 'Barasat', 'destination': 'Payradanga', 'price': 20},
            {'source': 'Barasat', 'destination': 'Shantipur', 'price': 25},
            {'source': 'Barasat', 'destination': 'Budge Budge', 'price': 15},
            {'source': 'Barasat', 'destination': 'Brace Bridge', 'price': 15},
            {'source': 'Barasat', 'destination': 'Santoshpur', 'price': 15},
            {'source': 'Barasat', 'destination': 'Akra', 'price': 15},
            {'source': 'Barasat', 'destination': 'Nungi', 'price': 15},
            {'source': 'Barasat', 'destination': 'Maheshtala', 'price': 15},
            {'source': 'Barasat', 'destination': 'Bauria', 'price': 20},
            {'source': 'Barasat', 'destination': 'Chengail', 'price': 20},
            {'source': 'Barasat', 'destination': 'Phuleswar', 'price': 20},
            {'source': 'Barasat', 'destination': 'Uluberia', 'price': 20},
            {'source': 'Barasat', 'destination': 'Mecheda', 'price': 25},
            {'source': 'Barasat', 'destination': 'Panskura', 'price': 30},
            {'source': 'Barasat', 'destination': 'Kharagpur', 'price': 35},
            {'source': 'Barasat', 'destination': 'Midnapore', 'price': 40},
            {'source': 'Barasat', 'destination': 'Haldia', 'price': 40},
            {'source': 'Barasat', 'destination': 'Digha', 'price': 50},
            {'source': 'Barasat', 'destination': 'Asansol', 'price': 50},
            {'source': 'Barasat', 'destination': 'Durgapur', 'price': 50},
            {'source': 'Barasat', 'destination': 'Bardhaman', 'price': 30},
            {'source': 'Barasat', 'destination': 'Bolpur Santiniketan', 'price': 35},
            {'source': 'Barasat', 'destination': 'Rampurhat', 'price': 40},
            {'source': 'Barasat', 'destination': 'Malda Town', 'price': 50},
            {'source': 'Barasat', 'destination': 'New Jalpaiguri', 'price': 70},
            {'source': 'Barasat', 'destination': 'Siliguri', 'price': 70},
            {'source': 'Barasat', 'destination': 'Darjeeling', 'price': 80},
            {'source': 'Barasat', 'destination': 'Kalimpong', 'price': 80},
            {'source': 'Barasat', 'destination': 'Gangtok', 'price': 90},
            {'source': 'Barasat', 'destination': 'Basirhat', 'price': 15},
            {'source': 'Barasat', 'destination': 'Hasnabad', 'price': 15},
            {'source': 'Barasat', 'destination': 'Taki Road', 'price': 15},
            {'source': 'Barasat', 'destination': 'Diamond Harbour', 'price': 20},
            {'source': 'Barasat', 'destination': 'Lakshmikantapur', 'price': 20},
            {'source': 'Barasat', 'destination': 'Kakdwip', 'price': 25},
            {'source': 'Barasat', 'destination': 'Namkhana', 'price': 25},
            
            {'source': 'Ashok Nagar Road', 'destination': 'Barasat', 'price': 5},
            {'source': 'Bagha Jatin', 'destination': 'Jadabpur', 'price': 5},
            {'source': 'Bagha Jatin', 'destination': 'New Garia', 'price': 5},
            {'source': 'Ballygunge Jn', 'destination': 'Dhakuria', 'price': 5},
            {'source': 'Ballygunge Jn', 'destination': 'Park Circus', 'price': 5},
            {'source': 'Ballygunge Jn', 'destination': 'Sealdah', 'price': 10},
            {'source': 'Bamangacchi', 'destination': 'Barasat', 'price': 5},
            {'source': 'Barasat', 'destination': 'Ashok Nagar Road', 'price': 5},
            {'source': 'Barasat', 'destination': 'Bamangacchi', 'price': 5},
            {'source': 'Barasat', 'destination': 'Barrackpore', 'price': 5},
            {'source': 'Barasat', 'destination': 'Belgharia', 'price': 10},
            {'source': 'Barasat', 'destination': 'Bira', 'price': 5},
            {'source': 'Barasat', 'destination': 'Bongaon', 'price': 15},
            {'source': 'Barasat', 'destination': 'Dakshineswar', 'price': 10},
            {'source': 'Barasat', 'destination': 'Dattapukur', 'price': 5},
            {'source': 'Barasat', 'destination': 'Dum Dum', 'price': 5},
            {'source': 'Barasat', 'destination': 'Gobardanga', 'price': 10},
            {'source': 'Barasat', 'destination': 'Guma', 'price': 5},
            {'source': 'Barasat', 'destination': 'Habra', 'price': 10},
            {'source': 'Barasat', 'destination': 'Howrah', 'price': 15},
            {'source': 'Barasat', 'destination': 'Hridaypur', 'price': 5},
            {'source': 'Barasat', 'destination': 'Kanchrapara', 'price': 20},
            {'source': 'Barasat', 'destination': 'Kankinara', 'price': 10},
            {'source': 'Barasat', 'destination': 'Khardah', 'price': 10},
            {'source': 'Barasat', 'destination': 'Madhyamgram', 'price': 5},
            {'source': 'Barasat', 'destination': 'Naihati', 'price': 20},
            {'source': 'Barasat', 'destination': 'New Barrackpore', 'price': 5},
            {'source': 'Barasat', 'destination': 'Sealdah', 'price': 10},
            {'source': 'Barasat', 'destination': 'Shyamnagar', 'price': 15},
            {'source': 'Barasat', 'destination': 'Sodepur', 'price': 10},
            {'source': 'Barasat', 'destination': 'Thakurnagar', 'price': 15},
            {'source': 'Barasat', 'destination': 'Titagarh', 'price': 10},
            {'source': 'Barrackpore', 'destination': 'Barasat', 'price': 5},
            {'source': 'Barrackpore', 'destination': 'Titagarh', 'price': 5},
            {'source': 'Belgharia', 'destination': 'Barasat', 'price': 10},
            {'source': 'Belgharia', 'destination': 'Dakshineswar', 'price': 10},
            {'source': 'Belgharia', 'destination': 'Sodepur', 'price': 5},
            {'source': 'Betberia Ghola', 'destination': 'Ghutiari Sharif', 'price': 5},
            {'source': 'Betberia Ghola', 'destination': 'Taldi', 'price': 5},
            {'source': 'Bidhannagar', 'destination': 'Bidhannagar Road', 'price': 5},
            {'source': 'Bidhannagar', 'destination': 'Dum Dum', 'price': 5},
            {'source': 'Bidhannagar', 'destination': 'Howrah', 'price': 15},
            {'source': 'Bidhannagar', 'destination': 'Sealdah', 'price': 10},
            {'source': 'Bidhannagar Road', 'destination': 'Bidhannagar', 'price': 5},
            {'source': 'Bidhannagar Road', 'destination': 'Sealdah', 'price': 10},
            {'source': 'Bidhannagar Road', 'destination': 'Sir Gurudass Banerjee', 'price': 5},
            {'source': 'Bidyadharpur', 'destination': 'Kalikapur', 'price': 5},
            {'source': 'Bidyadharpur', 'destination': 'Sonarpur Jn', 'price': 5},
            {'source': 'Bira', 'destination': 'Barasat', 'price': 5},
            {'source': 'Birati', 'destination': 'Dum Dum', 'price': 5},
            {'source': 'Birati', 'destination': 'Durganagar', 'price': 5},
            {'source': 'Bongaon', 'destination': 'Barasat', 'price': 15},
            {'source': 'Bongaon', 'destination': 'Gobardanga', 'price': 5},
            {'source': 'Bongaon', 'destination': 'Habra', 'price': 10},
            {'source': 'Bongaon', 'destination': 'Howrah', 'price': 20},
            {'source': 'Bongaon', 'destination': 'Sealdah', 'price': 20},
            {'source': 'Canning', 'destination': 'Chandpara', 'price': 5},
            {'source': 'Canning', 'destination': 'Howrah', 'price': 20},
            {'source': 'Canning', 'destination': 'Majerhat', 'price': 15},
            {'source': 'Canning', 'destination': 'Sealdah', 'price': 20},
            {'source': 'Chakdah', 'destination': 'Ranaghat', 'price': 10},
            {'source': 'Champahati', 'destination': 'Kalikapur', 'price': 5},
            {'source': 'Champahati', 'destination': 'Piali', 'price': 5},
            {'source': 'Chandpara', 'destination': 'Canning', 'price': 5},
            {'source': 'Chandpara', 'destination': 'Taldi', 'price': 5},
            {'source': 'Dakshineswar', 'destination': 'Barasat', 'price': 10},
            {'source': 'Dakshineswar', 'destination': 'Belgharia', 'price': 10},
            {'source': 'Dakshineswar', 'destination': 'Khardah', 'price': 10},
            {'source': 'Dattapukur', 'destination': 'Barasat', 'price': 5},
            {'source': 'Dattapukur', 'destination': 'Habra', 'price': 5},
            {'source': 'Dattapukur', 'destination': 'Madhyamgram', 'price': 5},
            {'source': 'Dattapukur', 'destination': 'Sealdah', 'price': 10},
            {'source': 'Dhakuria', 'destination': 'Ballygunge Jn', 'price': 5},
            {'source': 'Dhakuria', 'destination': 'Jadabpur', 'price': 5},
            {'source': 'Dum Dum', 'destination': 'Barasat', 'price': 5},
            {'source': 'Dum Dum', 'destination': 'Bidhannagar', 'price': 5},
            {'source': 'Dum Dum', 'destination': 'Birati', 'price': 5},
            {'source': 'Dum Dum', 'destination': 'Durganagar', 'price': 5},
            {'source': 'Dum Dum', 'destination': 'Howrah', 'price': 10},
            {'source': 'Dum Dum', 'destination': 'Kolkata', 'price': 10},
            {'source': 'Dum Dum', 'destination': 'Madhyamgram', 'price': 5},
            {'source': 'Dum Dum', 'destination': 'Sealdah', 'price': 5},
            {'source': 'Dum Dum', 'destination': 'Sodepur', 'price': 10},
            {'source': 'Dum Dum Cantonment', 'destination': 'Durganagar', 'price': 5},
            {'source': 'Durganagar', 'destination': 'Birati', 'price': 5},
            {'source': 'Durganagar', 'destination': 'Dum Dum', 'price': 5},
            {'source': 'Durganagar', 'destination': 'Dum Dum Cantonment', 'price': 5},
            {'source': 'Garia', 'destination': 'Narendrapur', 'price': 10},
            {'source': 'Garia', 'destination': 'New Garia', 'price': 5},
            {'source': 'Gaurdaha', 'destination': 'Ghutiari Sharif', 'price': 5},
            {'source': 'Gaurdaha', 'destination': 'Piali', 'price': 5},
            {'source': 'Ghutiari Sharif', 'destination': 'Betberia Ghola', 'price': 5},
            {'source': 'Ghutiari Sharif', 'destination': 'Gaurdaha', 'price': 5},
            {'source': 'Gobardanga', 'destination': 'Barasat', 'price': 10},
            {'source': 'Gobardanga', 'destination': 'Bongaon', 'price': 5},
            {'source': 'Gobardanga', 'destination': 'Thakurnagar', 'price': 5},
            {'source': 'Guma', 'destination': 'Barasat', 'price': 5},
            {'source': 'Habra', 'destination': 'Barasat', 'price': 10},
            {'source': 'Habra', 'destination': 'Bongaon', 'price': 10},
            {'source': 'Habra', 'destination': 'Dattapukur', 'price': 5},
            {'source': 'Habra', 'destination': 'Sealdah', 'price': 10},
            {'source': 'Howrah', 'destination': 'Barasat', 'price': 15},
            {'source': 'Howrah', 'destination': 'Bidhannagar', 'price': 15},
            {'source': 'Howrah', 'destination': 'Bongaon', 'price': 20},
            {'source': 'Howrah', 'destination': 'Canning', 'price': 20},
            {'source': 'Howrah', 'destination': 'Dum Dum', 'price': 10},
            {'source': 'Howrah', 'destination': 'Kolkata', 'price': 5},
            {'source': 'Howrah', 'destination': 'Ranaghat', 'price': 20},
            {'source': 'Howrah', 'destination': 'Sealdah', 'price': 5},
            {'source': 'Hridaypur', 'destination': 'Barasat', 'price': 5},
            {'source': 'Jadabpur', 'destination': 'Bagha Jatin', 'price': 5},
            {'source': 'Jadabpur', 'destination': 'Dhakuria', 'price': 5},
            {'source': 'Kachrapara', 'destination': 'Naihati', 'price': 10},
            {'source': 'Kalikapur', 'destination': 'Bidyadharpur', 'price': 5},
            {'source': 'Kalikapur', 'destination': 'Champahati', 'price': 5},
            {'source': 'Kalyani', 'destination': 'Krishnanagar', 'price': 10},
            {'source': 'Kanchrapara', 'destination': 'Barasat', 'price': 20},
            {'source': 'Kanchrapara', 'destination': 'Naihati', 'price': 10},
            {'source': 'Kanchrapara', 'destination': 'Ranaghat', 'price': 15},
            {'source': 'Kanchrapara', 'destination': 'Sealdah', 'price': 20},
            {'source': 'Kankinara', 'destination': 'Barasat', 'price': 10},
            {'source': 'Kankinara', 'destination': 'Khardah', 'price': 10},
            {'source': 'Khardah', 'destination': 'Barasat', 'price': 10},
            {'source': 'Khardah', 'destination': 'Dakshineswar', 'price': 10},
            {'source': 'Khardah', 'destination': 'Kankinara', 'price': 10},
            {'source': 'Kolkata', 'destination': 'Dum Dum', 'price': 10},
            {'source': 'Kolkata', 'destination': 'Howrah', 'price': 5},
            {'source': 'Kolkata', 'destination': 'Sealdah', 'price': 5},
            {'source': 'Krishnanagar', 'destination': 'Kalyani', 'price': 10},
            {'source': 'Krishnanagar', 'destination': 'Ranaghat', 'price': 5},
            {'source': 'Krishnanagar', 'destination': 'Sealdah', 'price': 20},
            {'source': 'Machhalandapur', 'destination': 'Ranaghat', 'price': 15},
            {'source': 'Machhalandapur', 'destination': 'Sanhati', 'price': 5},
            {'source': 'Madhyamgram', 'destination': 'Barasat', 'price': 5},
            {'source': 'Madhyamgram', 'destination': 'Dattapukur', 'price': 5},
            {'source': 'Madhyamgram', 'destination': 'Dum Dum', 'price': 5},
            {'source': 'Majerhat', 'destination': 'Canning', 'price': 15},
            {'source': 'Naihati', 'destination': 'Barasat', 'price': 20},
            {'source': 'Naihati', 'destination': 'Kachrapara', 'price': 10},
            {'source': 'Naihati', 'destination': 'Kanchrapara', 'price': 10},
            {'source': 'Naihati', 'destination': 'Sealdah', 'price': 15},
            {'source': 'Naihati', 'destination': 'Shyamnagar', 'price': 5},
            {'source': 'Naihati', 'destination': 'Thakurnagar', 'price': 10},
            {'source': 'Narendrapur', 'destination': 'Garia', 'price': 10},
            {'source': 'Narendrapur', 'destination': 'Sonarpur Jn', 'price': 5},
            {'source': 'New Barrackpore', 'destination': 'Barasat', 'price': 5},
            {'source': 'New Garia', 'destination': 'Bagha Jatin', 'price': 5},
            {'source': 'New Garia', 'destination': 'Garia', 'price': 5},
            {'source': 'Park Circus', 'destination': 'Ballygunge Jn', 'price': 5},
            {'source': 'Park Circus', 'destination': 'Sealdah', 'price': 5},
            {'source': 'Piali', 'destination': 'Champahati', 'price': 5},
            {'source': 'Piali', 'destination': 'Gaurdaha', 'price': 5},
            {'source': 'Ranaghat', 'destination': 'Chakdah', 'price': 10},
            {'source': 'Ranaghat', 'destination': 'Howrah', 'price': 20},
            {'source': 'Ranaghat', 'destination': 'Kanchrapara', 'price': 15},
            {'source': 'Ranaghat', 'destination': 'Krishnanagar', 'price': 5},
            {'source': 'Ranaghat', 'destination': 'Machhalandapur', 'price': 15},
            {'source': 'Ranaghat', 'destination': 'Sealdah', 'price': 20},
            {'source': 'Sanhati', 'destination': 'Machhalandapur', 'price': 5},
            {'source': 'Sanhati', 'destination': 'Sir Gurudass Banerjee', 'price': 10},
            {'source': 'Sealdah', 'destination': 'Ballygunge Jn', 'price': 10},
            {'source': 'Sealdah', 'destination': 'Barasat', 'price': 10},
            {'source': 'Sealdah', 'destination': 'Bidhannagar', 'price': 10},
            {'source': 'Sealdah', 'destination': 'Bidhannagar Road', 'price': 10},
            {'source': 'Sealdah', 'destination': 'Bongaon', 'price': 20},
            {'source': 'Sealdah', 'destination': 'Canning', 'price': 20},
            {'source': 'Sealdah', 'destination': 'Dattapukur', 'price': 10},
            {'source': 'Sealdah', 'destination': 'Dum Dum', 'price': 5},
            {'source': 'Sealdah', 'destination': 'Habra', 'price': 10},
            {'source': 'Sealdah', 'destination': 'Howrah', 'price': 5},
            {'source': 'Sealdah', 'destination': 'Kanchrapara', 'price': 20},
            {'source': 'Sealdah', 'destination': 'Kolkata', 'price': 5},
            {'source': 'Sealdah', 'destination': 'Krishnanagar', 'price': 20},
            {'source': 'Sealdah', 'destination': 'Naihati', 'price': 15},
            {'source': 'Sealdah', 'destination': 'Park Circus', 'price': 5},
            {'source': 'Sealdah', 'destination': 'Ranaghat', 'price': 20},
            {'source': 'Sealdah', 'destination': 'Sonarpur Jn', 'price': 15},
            {'source': 'Shyamnagar', 'destination': 'Barasat', 'price': 15},
            {'source': 'Shyamnagar', 'destination': 'Naihati', 'price': 5},
            {'source': 'Sir Gurudass Banerjee', 'destination': 'Bidhannagar Road', 'price': 5},
            {'source': 'Sir Gurudass Banerjee', 'destination': 'Sanhati', 'price': 10},
            {'source': 'Sodepur', 'destination': 'Barasat', 'price': 10},
            {'source': 'Sodepur', 'destination': 'Belgharia', 'price': 5},
            {'source': 'Sodepur', 'destination': 'Dum Dum', 'price': 10},
            {'source': 'Sodepur', 'destination': 'Titagarh', 'price': 5},
            {'source': 'Sonarpur Jn', 'destination': 'Bidyadharpur', 'price': 5},
            {'source': 'Sonarpur Jn', 'destination': 'Narendrapur', 'price': 5},
            {'source': 'Sonarpur Jn', 'destination': 'Sealdah', 'price': 15},
            {'source': 'Taldi', 'destination': 'Betberia Ghola', 'price': 5},
            {'source': 'Taldi', 'destination': 'Chandpara', 'price': 5},
            {'source': 'Thakurnagar', 'destination': 'Barasat', 'price': 15},
            {'source': 'Thakurnagar', 'destination': 'Gobardanga', 'price': 5},
            {'source': 'Thakurnagar', 'destination': 'Naihati', 'price': 10},
            {'source': 'Titagarh', 'destination': 'Barasat', 'price': 10},
            {'source': 'Titagarh', 'destination': 'Barrackpore', 'price': 5},
            {'source': 'Titagarh', 'destination': 'Sodepur', 'price': 5},

        ]

        for route_data in routes:
            Route.objects.get_or_create(**route_data)

        self.stdout.write(self.style.SUCCESS('Successfully populated the database with initial route data'))
